/*

Caches are small, quick memories that hold copies of data found in the system’s main memory.

The easiest way to design a multiprocessor scheduler is to approach to reuse the 
basic structure for single processor scheduling by putting all jobs into a single queue, 
which we call single-queue multiprocessor scheduling, or SQMS.


Each virtual address that is generated by the process is added to the contents of the 
base register to provide the physical address that can be issued to the system.
virtual address + base = physical address

the basic event-based method is immune to concurrency issues that plague threaded programs.
True.

Which of the following are necessary hardware support for efficient address translation?(Multiple answers are possible)
Ability to Raise Exceptions
Kernel Mode
Base and Bounds Registers


*/